### ISSUE TITLE
Can't follow a Shoot actor

### ISSUE THREAD

**Issue by silverpill** [MaddyUnderStars/shoot#58]
Hello, I am sending a `Follow` activity from Mitra server.

Status code: 400
Error message: `If message provided, digest must be too and vice versa`

**Comment by MaddyUnderStars** [comment]
Does Mitra send digest headers for signed requests? If not, why?

**Comment by MaddyUnderStars** [comment]
My quick glance at Mitra source says yes... I'll have to investigate more later. Could you please send the http request data here? headers specifically

**Comment by silverpill** [comment]
Can't show the exact headers right now, but we send `Content-Type`, `User-Agent`, `Host`, `Date`, `Digest` and `Signature`.

Digest is `SHA-256={digest_b64}`
Content type is `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`

**Comment by MaddyUnderStars** [comment]
Hm. That error is just two if statements

https://github.com/MaddyUnderStars/shoot/blob/55baa7a316e65ee0427b426633b417ad94d97957/src/util/activitypub/httpsig.ts#L163-L167

where `rawActivity` is the raw http body content. not really sure what's going wrong here. Is there a public Mitra instance? I was going to set it up locally, but my VPS is ARM, and neither the docker image or deb package installs lol.

Otherwise, I can install from source later. Possibly later tonight/tomorrow.

**Comment by MaddyUnderStars** [comment]
Thanks for that. I've fixed this specific error in f30083a57751e4e4cf91ed52e8a92381d6c8a1e9, turns out it was because bodyParser doesn't like it when you pass attributes in a content type for it to accept (`bodyParser.raw({ type: 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"' })` causes it to compare `application/ld+json` to the full string, which fails).

I'm getting a problem when Accepting follows though, which I would appreciate your help with. I'll make a new issue now

**Comment by silverpill** [comment]
@MaddyUnderStars It seems the instance I was testing against is not up to date (still getting the same error there). Do you have an "official" instance where I can follow an actor?

**Comment by MaddyUnderStars** [comment]
Unfortunately no. I could host one for testing later today if you're interested

**Comment by anotherdoesnm** [comment]
@silverpill yeah, i didn't updating it, waiting until some issues are closee

**Comment by silverpill** [comment]
@MaddyUnderStars Thanks! My `Follow` has been delivered successfully to `maddy@chat.understars.dev`.

However, I still can't follow @anotherdoesnm - the error is `Relationship could not be found`.

**Comment by silverpill** [comment]
>I have silverpill in my list

This is also interesting -- I didn't see your follow request.

**Comment by silverpill** [comment]
Yup, I also don't have discord. Matrix and xmpp are fine with me.
